# Generated by Django 5.1.4 on 2024-12-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_price_item_understanding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='watched',
        ),
    ]
